// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl-FtfbyK53Ec2F8y2CyUviOmGGnFcuoo',
    appId: '1:282230859534:android:72235ffd098e363f70995f',
    messagingSenderId: '282230859534',
    projectId: 'no-name-note',
    storageBucket: 'no-name-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_dAux0A3vieM7Grd5Po2dtituVy1Qbiw',
    appId: '1:282230859534:ios:b47bd53e6f77412970995f',
    messagingSenderId: '282230859534',
    projectId: 'no-name-note',
    storageBucket: 'no-name-note.appspot.com',
    androidClientId: '282230859534-5uap11jnmdam2ub00ctt0qp9harsr4tq.apps.googleusercontent.com',
    iosClientId: '282230859534-rp5h7vlekd7fg7eriqk45rodc7ce54u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noNameNote',
  );
}
